/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Src;

import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class ProjetoPOO extends javax.swing.JFrame {
    
    protected ArrayList <Pessoa> pessoas;
    protected ArrayList <Projeto> projetos;
    
    public ProjetoPOO() throws IOException {
        pessoas = new ArrayList<>();
        projetos = new ArrayList<>();

        lerPessoas(pessoas);
        /*
        try{
            projetos = lerProjetosObj();
        }
        catch(NullPointerException | IOException e) {
            projetos = new ArrayList<>();
        }*/
        this.pessoas = pessoas;
        this.projetos = projetos;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPrincipal = new javax.swing.JPanel();
        Título = new javax.swing.JLabel();
        CriarProj = new javax.swing.JButton();
        ProjNaoConc = new javax.swing.JButton();
        ProjConc = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        ProcurarProj = new javax.swing.JButton();
        ProcurarProjeto = new javax.swing.JPanel();
        Título1 = new javax.swing.JLabel();
        CriarProjeto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cpNome = new javax.swing.JTextField();
        cpAcronimo = new javax.swing.JTextField();
        cpDiaIn = new javax.swing.JTextField();
        cpDuracaoprev = new javax.swing.JTextField();
        VoltarCriarProj = new javax.swing.JButton();
        SeguinteCriarProj = new javax.swing.JButton();
        cpMesIn = new javax.swing.JTextField();
        cpAnoIn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cpMesFim = new javax.swing.JTextField();
        cpAnoFim = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cpDiaFim = new javax.swing.JTextField();
        CriarProjeto2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        addInvPrinc = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        invest = new javax.swing.JScrollPane();
        addInvest = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        addBols = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        MenuPrincipal.setPreferredSize(new java.awt.Dimension(700, 500));

        Título.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Título.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Título.setText("Menu Principal");

        CriarProj.setText("Criar um projeto");
        CriarProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarProjActionPerformed(evt);
            }
        });

        ProjNaoConc.setText("Listar projetos não concluidos");
        ProjNaoConc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProjNaoConcActionPerformed(evt);
            }
        });

        ProjConc.setText("Listar projetos concluidos");
        ProjConc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProjConcActionPerformed(evt);
            }
        });

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        ProcurarProj.setText("Procurar projeto");
        ProcurarProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcurarProjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPrincipalLayout = new javax.swing.GroupLayout(MenuPrincipal);
        MenuPrincipal.setLayout(MenuPrincipalLayout);
        MenuPrincipalLayout.setHorizontalGroup(
            MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Título, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(CriarProj)
                    .addComponent(ProjNaoConc)
                    .addComponent(ProjConc)
                    .addComponent(ProcurarProj))
                .addGap(261, 261, 261))
        );
        MenuPrincipalLayout.setVerticalGroup(
            MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPrincipalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Título, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(CriarProj)
                .addGap(56, 56, 56)
                .addComponent(ProcurarProj)
                .addGap(52, 52, 52)
                .addComponent(ProjNaoConc)
                .addGap(58, 58, 58)
                .addComponent(ProjConc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(Sair)
                .addContainerGap())
        );

        getContentPane().add(MenuPrincipal, "card2");

        ProcurarProjeto.setPreferredSize(new java.awt.Dimension(700, 500));

        Título1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Título1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Título1.setText("Menu Principal");

        javax.swing.GroupLayout ProcurarProjetoLayout = new javax.swing.GroupLayout(ProcurarProjeto);
        ProcurarProjeto.setLayout(ProcurarProjetoLayout);
        ProcurarProjetoLayout.setHorizontalGroup(
            ProcurarProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProcurarProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Título1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addContainerGap())
        );
        ProcurarProjetoLayout.setVerticalGroup(
            ProcurarProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProcurarProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Título1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(454, Short.MAX_VALUE))
        );

        getContentPane().add(ProcurarProjeto, "card4");

        CriarProjeto.setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Criar novo Projeto");

        jLabel2.setText("Nome:");

        jLabel3.setText("Acrónimo:");

        jLabel4.setText("Data de Inicio:");

        jLabel5.setText("Duração prevista:");

        cpNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpNomeActionPerformed(evt);
            }
        });

        cpAcronimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpAcronimoActionPerformed(evt);
            }
        });

        cpDiaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpDiaInActionPerformed(evt);
            }
        });

        VoltarCriarProj.setText("Voltar");
        VoltarCriarProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarCriarProjActionPerformed(evt);
            }
        });

        SeguinteCriarProj.setText("Seguinte");
        SeguinteCriarProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguinteCriarProjActionPerformed(evt);
            }
        });

        jLabel6.setText("/");

        jLabel7.setText("/");

        jLabel12.setText("/");

        jLabel13.setText("Data de Fim:");

        jLabel14.setText("/");

        cpDiaFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpDiaFimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CriarProjetoLayout = new javax.swing.GroupLayout(CriarProjeto);
        CriarProjeto.setLayout(CriarProjetoLayout);
        CriarProjetoLayout.setHorizontalGroup(
            CriarProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CriarProjetoLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addGap(104, 104, 104))
            .addGroup(CriarProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VoltarCriarProj, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SeguinteCriarProj, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(CriarProjetoLayout.createSequentialGroup()
                .addGroup(CriarProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CriarProjetoLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(CriarProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CriarProjetoLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpAcronimo))
                            .addGroup(CriarProjetoLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpNome, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(CriarProjetoLayout.createSequentialGroup()
                        .addGroup(CriarProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CriarProjetoLayout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CriarProjetoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(CriarProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CriarProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CriarProjetoLayout.createSequentialGroup()
                                .addComponent(cpDiaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpMesIn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpAnoIn))
                            .addComponent(cpDuracaoprev, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CriarProjetoLayout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(cpDiaFim, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpMesFim, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpAnoFim, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CriarProjetoLayout.setVerticalGroup(
            CriarProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CriarProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(89, 89, 89)
                .addGroup(CriarProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cpNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(CriarProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cpAcronimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(CriarProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cpDiaIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpMesIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpAnoIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(36, 36, 36)
                .addGroup(CriarProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cpDiaFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpMesFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpAnoFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addGap(28, 28, 28)
                .addGroup(CriarProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpDuracaoprev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(CriarProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VoltarCriarProj)
                    .addComponent(SeguinteCriarProj))
                .addContainerGap())
        );

        getContentPane().add(CriarProjeto, "card3");

        CriarProjeto2.setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Criar novo Projeto");

        addInvPrinc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInvPrincActionPerformed(evt);
            }
        });

        jLabel9.setText("Investigador Principal:");

        jLabel10.setText("Adicionar Investigadores:");

        jLabel11.setText("Adicionar Bolseiros:");

        invest.setViewportView(addInvest);

        jScrollPane3.setViewportView(addBols);

        jButton1.setText("Criar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CriarProjeto2Layout = new javax.swing.GroupLayout(CriarProjeto2);
        CriarProjeto2.setLayout(CriarProjeto2Layout);
        CriarProjeto2Layout.setHorizontalGroup(
            CriarProjeto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CriarProjeto2Layout.createSequentialGroup()
                .addGroup(CriarProjeto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CriarProjeto2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(CriarProjeto2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(addInvPrinc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(54, 54, 54)))
                .addGroup(CriarProjeto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(invest, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CriarProjeto2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CriarProjeto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CriarProjeto2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CriarProjeto2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
            .addGroup(CriarProjeto2Layout.createSequentialGroup()
                .addGroup(CriarProjeto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CriarProjeto2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CriarProjeto2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        CriarProjeto2Layout.setVerticalGroup(
            CriarProjeto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CriarProjeto2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(70, 70, 70)
                .addGroup(CriarProjeto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(38, 38, 38)
                .addGroup(CriarProjeto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addInvPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3)
                    .addComponent(invest, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(CriarProjeto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        getContentPane().add(CriarProjeto2, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProjNaoConcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProjNaoConcActionPerformed
        MenuPrincipal.setVisible(false);
        //ListarProjetosNaoConcluidos.setVisible(true);
    }//GEN-LAST:event_ProjNaoConcActionPerformed

    private void ProjConcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProjConcActionPerformed
        MenuPrincipal.setVisible(false);
        //ListarProjetosConcluidos.setVisible(true);
    }//GEN-LAST:event_ProjConcActionPerformed

    private void CriarProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarProjActionPerformed
        MenuPrincipal.setVisible(false);
        CriarProjeto.setVisible(true);
    }//GEN-LAST:event_CriarProjActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void cpNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpNomeActionPerformed

    private void ProcurarProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcurarProjActionPerformed
        MenuPrincipal.setVisible(false);
        ProcurarProjeto.setVisible(true);
    }//GEN-LAST:event_ProcurarProjActionPerformed

    private void VoltarCriarProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarCriarProjActionPerformed
        CriarProjeto.setVisible(false);
        MenuPrincipal.setVisible(true);
    }//GEN-LAST:event_VoltarCriarProjActionPerformed

    private void SeguinteCriarProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguinteCriarProjActionPerformed
        int aux=0;
        cpNome.setBackground(null);
        cpAcronimo.setBackground(null);
        cpDiaIn.setBackground(null);
        cpMesIn.setBackground(null);
        cpAnoIn.setBackground(null);
        cpDuracaoprev.setBackground(null);
        if (cpNome.getText().equals("")){
            cpNome.setBackground(Color.red);
            aux++;
        }
        else{
            for (int i = 0; i < projetos.size();i++){
                if (projetos.get(i).getNome().equals(cpNome.getText())){
                    cpNome.setBackground(Color.red);
                    JOptionPane.showInputDialog("Nome já existente!");
                    cpNome.setBackground(null);
                    aux++;
                    break;
                }
            }
        }
        
        if (cpAcronimo.getText().equals("")){
            cpAcronimo.setBackground(Color.red);
            aux++;
        }
        try{
        if (cpDiaIn.getText(). equals("") || Integer.parseInt(cpDiaIn.getText())>31 || Integer.parseInt(cpDiaIn.getText())<1){
            cpDiaIn.setBackground(Color.red);
            aux++;
        }}
        catch (Exception e){
            cpDiaIn.setBackground(Color.red);
            aux++;
        }
        try{
        if (cpMesIn.getText(). equals("") || Integer.parseInt(cpMesIn.getText())>12 || Integer.parseInt(cpMesIn.getText())<1){
            cpMesIn.setBackground(Color.red);
            aux++;
        }}
        catch (Exception e){
            cpMesIn.setBackground(Color.red);
            aux++;
        }
        try{
        if (cpAnoIn.getText(). equals("") || Integer.parseInt(cpAnoIn.getText())<0){
            cpAnoIn.setBackground(Color.red);
            aux++;
        }}
        catch (Exception e){
            cpAnoIn.setBackground(Color.red);
            aux++;
        }
        
        try{
        if (cpDiaFim.getText(). equals("") || Integer.parseInt(cpDiaFim.getText())>31 || Integer.parseInt(cpDiaFim.getText())<1){
            cpDiaFim.setBackground(Color.red);
            aux++;
        }}
        catch (Exception e){
            cpDiaFim.setBackground(Color.red);
            aux++;
        }
        try{
        if (cpMesFim.getText(). equals("") || Integer.parseInt(cpMesFim.getText())>12 || Integer.parseInt(cpMesFim.getText())<1){
            cpMesFim.setBackground(Color.red);
            aux++;
        }}
        catch (Exception e){
            cpMesFim.setBackground(Color.red);
            aux++;
        }
        try{
        if (cpAnoFim.getText(). equals("") || Integer.parseInt(cpAnoFim.getText())<0){
            cpAnoFim.setBackground(Color.red);
            aux++;
        }}
        catch (Exception e){
            cpAnoFim.setBackground(Color.red);
            aux++;
        }
        
        try{
        if (cpDuracaoprev.getText(). equals("") || Integer.parseInt(cpDuracaoprev.getText())<1){
            cpDuracaoprev.setBackground(Color.red);
            aux++;
        }}
        catch (Exception e){
            cpDuracaoprev.setBackground(Color.red);
            aux++;
        }
        if (aux > 0){
            JOptionPane.showInputDialog("Por favor verifique os campos a vermelho.");
        }
        else{
            int aux2 = 0;
            String dd[] = new String[pessoas.size()];
            
            for(int j=0;j<pessoas.size();j++){
                if (pessoas.get(j).getTipo().equals("Doc")){
                    dd[aux2] = (pessoas.get(j).getNome());
                    aux2++;
                }
            }
            addInvest.setListData(dd);
            
            aux2 = 0;
            dd = new String[pessoas.size()];
            
            for(int j=0;j<pessoas.size();j++){
                if (pessoas.get(j).getTipo().equals("Doc")){
                    dd[aux2] = (pessoas.get(j).getNome());
                    aux2++;
                }
            }
            addInvPrinc.setModel(new javax.swing.DefaultComboBoxModel<>(dd));
            
            aux2 = 0;
            dd = new String[pessoas.size()];
            
            for(int j=0;j<pessoas.size();j++){
                if (pessoas.get(j).getTipo().equals("B")){
                    
                    Bolseiro bolseiro= (Bolseiro) pessoas.get(j);
                    if(bolseiro.getDataInicBolsa()== null){
                        dd[aux2] = (pessoas.get(j).getNome());
                        aux2++;
                        
                    }
                    
                }
            }
            addBols.setListData(dd);
            
            CriarProjeto.setVisible(false);
            CriarProjeto2.setVisible(true);
        }
    }//GEN-LAST:event_SeguinteCriarProjActionPerformed

    private void cpAcronimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpAcronimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpAcronimoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<Pessoa> pp = new ArrayList<>();
        List<String> aux1 = addBols.getSelectedValuesList();
        List<String> aux2 = addInvest.getSelectedValuesList();

        Docente docente = null;
        for (int i=0;i<pessoas.size();i++){
            if(pessoas.get(i).getNome().equals(addInvPrinc.getSelectedItem())){
                docente = (Docente) pessoas.get(i);
                break;
            }
        }
        for (int i=0;i<aux1.size();i++){
            for (int j=0;j<pessoas.size();j++){
                if(pessoas.get(j).getNome().equals(aux1.get(i))){
                    pp.add(pessoas.get(j));
                }
            }
        }
        for (int i=0;i<aux2.size();i++){
            for (int j=0;j<pessoas.size();j++){
                if(pessoas.get(j).getNome().equals(aux2.get(i))){
                    pp.add(pessoas.get(j));
                }
            }
        }
        Projeto projeto = new Projeto(cpNome.getText(),cpAcronimo.getText(), new Data(Integer.parseInt(cpDiaIn.getText()),Integer.parseInt(cpMesIn.getText()),Integer.parseInt(cpAnoIn.getText())), new Data(Integer.parseInt(cpDiaFim.getText()),Integer.parseInt(cpMesFim.getText()),Integer.parseInt(cpAnoFim.getText())), Integer.parseInt(cpDuracaoprev.getText()), docente, pp);
        projetos.add(projeto);
        CriarProjeto2.setVisible(false);
        MenuPrincipal.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addInvPrincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInvPrincActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addInvPrincActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CriarProjeto2.setVisible(false);
        CriarProjeto.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cpDiaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpDiaInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpDiaInActionPerformed

    private void cpDiaFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpDiaFimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpDiaFimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void lerPessoas(ArrayList<Pessoa> pessoas) throws IOException {
        FicheiroDeTexto fichPessoas = new FicheiroDeTexto();
        fichPessoas.abreLeitura("fichPessoas.txt");

        String linhafich;
        linhafich = fichPessoas.leLinha();
        while(linhafich != null){
            String parts[] = linhafich.split("/");
            String partPessoa[] = parts[0].split(";");  
            if (partPessoa[2].equals("D")) {
                String partDocente[] = parts[1].split(";");
                Docente docente = new Docente(Integer.parseInt(partDocente[0]), partDocente[1], partPessoa[0], partPessoa[1]);
                pessoas.add(docente);
            }
            else if (partPessoa[2].equals("B")) {
                String partBolseiro[] = parts[1].split(";");
                if(partBolseiro[0].equals(" ")){
                    if(partBolseiro[3].equals("D")){
                        Doutorado doutorado = new Doutorado(partPessoa[0], partPessoa[1]);
                        pessoas.add(doutorado);
                    }
                    else if(parts[2].equals(" ")){
                        if(partBolseiro[3].equals("L")){
                            Licenciado licenciado = new Licenciado(partPessoa[0], partPessoa[1]);
                            pessoas.add(licenciado);
                        }
                        else if(partBolseiro[3].equals("M")){
                            Mestrado mestrado = new Mestrado(partPessoa[0], partPessoa[1]);
                            pessoas.add(mestrado);
                        }
                    }
                }
                else{
                    String partDataIni[] = partBolseiro[0].split(":");
                    String partDataFim[] = partBolseiro[1].split(":");
                    Data dataIni = new Data(Integer.parseInt(partDataIni[0]),Integer.parseInt(partDataIni[1]),Integer.parseInt(partDataIni[2]));
                    Data dataFim = new Data(Integer.parseInt(partDataFim[0]),Integer.parseInt(partDataFim[1]),Integer.parseInt(partDataFim[2]));
                    if(partBolseiro[3].equals("D")){
                        Doutorado doutorado = new Doutorado(dataIni, dataFim,Integer.parseInt(partBolseiro[2]) , partPessoa[0], partPessoa[1]);
                        pessoas.add(doutorado);
                    }
                    else if(parts[2].equals(" ")){
                        if(partBolseiro[3].equals("L")){
                            Licenciado licenciado = new Licenciado(dataIni, dataFim,Integer.parseInt(partBolseiro[2]) , partPessoa[0], partPessoa[1]);
                            pessoas.add(licenciado);
                        }
                        else if(partBolseiro[3].equals("M")){
                            Mestrado mestrado = new Mestrado(dataIni, dataFim,Integer.parseInt(partBolseiro[2]) , partPessoa[0], partPessoa[1]);
                            pessoas.add(mestrado);
                        }
                    }
                    else{
                        String partOrientador[] = parts[2].split(";");
                        ArrayList<String> orientadores = new ArrayList<>();
                        for(int i=0; i<partOrientador.length;i++){
                            orientadores.add(partOrientador[i]);
                        }
                        if(partBolseiro[3].equals("L")){
                            Licenciado licenciado = new Licenciado(orientadores, dataIni, dataFim,Integer.parseInt(partBolseiro[2]) , partPessoa[0], partPessoa[1]);
                            pessoas.add(licenciado);
                        }
                        else if(partBolseiro[3].equals("M")){
                            Mestrado mestrado = new Mestrado(orientadores, dataIni, dataFim,Integer.parseInt(partBolseiro[2]) , partPessoa[0], partPessoa[1]);
                            pessoas.add(mestrado);
                        }
                    }
                }
            }
            
            linhafich = fichPessoas.leLinha();
        }
        fichPessoas.fechaLeitura();
    }
    public static void main(String args[]) throws IOException {
       
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ProjetoPOO().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ProjetoPOO.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CriarProj;
    private javax.swing.JPanel CriarProjeto;
    private javax.swing.JPanel CriarProjeto2;
    private javax.swing.JPanel MenuPrincipal;
    private javax.swing.JButton ProcurarProj;
    private javax.swing.JPanel ProcurarProjeto;
    private javax.swing.JButton ProjConc;
    private javax.swing.JButton ProjNaoConc;
    private javax.swing.JButton Sair;
    private javax.swing.JButton SeguinteCriarProj;
    private javax.swing.JLabel Título;
    private javax.swing.JLabel Título1;
    private javax.swing.JButton VoltarCriarProj;
    private javax.swing.JList<String> addBols;
    private javax.swing.JComboBox<String> addInvPrinc;
    public javax.swing.JList<String> addInvest;
    private javax.swing.JTextField cpAcronimo;
    private javax.swing.JTextField cpAnoFim;
    private javax.swing.JTextField cpAnoIn;
    private javax.swing.JTextField cpDiaFim;
    private javax.swing.JTextField cpDiaIn;
    private javax.swing.JTextField cpDuracaoprev;
    private javax.swing.JTextField cpMesFim;
    private javax.swing.JTextField cpMesIn;
    private javax.swing.JTextField cpNome;
    private javax.swing.JScrollPane invest;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
